version: "3"
services:
  springboot-app:
    image: springboot-app
    restart: always
    build: .
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306

  mysqldb:
    container_name: mysqldb
    image: mysql:8.3.0
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: groceryapp
      MYSQL_ROOT_PASSWORD: root